// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ReadParentVector
String ReadParentVector(String file_path, size_t mutation_count);
RcppExport SEXP _ScRNACloneEvaluation_ReadParentVector(SEXP file_pathSEXP, SEXP mutation_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< size_t >::type mutation_count(mutation_countSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadParentVector(file_path, mutation_count));
    return rcpp_result_gen;
END_RCPP
}
// GetChains
NumericVector GetChains(NumericVector parent_vector);
RcppExport SEXP _ScRNACloneEvaluation_GetChains(SEXP parent_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type parent_vector(parent_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(GetChains(parent_vector));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ScRNACloneEvaluation_ReadParentVector", (DL_FUNC) &_ScRNACloneEvaluation_ReadParentVector, 2},
    {"_ScRNACloneEvaluation_GetChains", (DL_FUNC) &_ScRNACloneEvaluation_GetChains, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ScRNACloneEvaluation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
